### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#14]
[11:47:20 ERROR]: Could not pass event BlockBreakEvent to Drop2Inventory v3.6
java.lang.IllegalArgumentException: Cannot drop air
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.EntityItem.setItemStack(EntityItem.java:409) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.EntityItem.<init>(EntityItem.java:42) ~[patched_1.13.2.jar:git-Paper-561]
        at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.dropItem(CraftWorld.java:348) ~[patched_1.13.2.jar:git-Paper-561]
        at de.jeffclan.Drop2Inventory.DropHandler.drop2inventory(DropHandler.java:69) ~[?:?]
        at de.jeffclan.Drop2Inventory.Listener.onBlockBreak(Listener.java:162) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor81.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:67) ~[patched_1.13.2.jar:git-Paper-561]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-561]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-561]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:198) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1287) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-561]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-561]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-561]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by mfnalex** [comment]
How did this happen?

**Comment by mfnalex** [comment]
fixed
