### ISSUE TITLE
air error

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#17]
[17:35:39 ERROR]: Could not pass event BlockBreakEvent to Drop2Inventory v3.8
java.lang.IllegalArgumentException: Cannot drop air
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityItem.setItemStack(EntityItem.java:410) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityItem.<init>(EntityItem.java:42) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.dropItem(CraftWorld.java:370) ~[patched_1.13.2.jar:git-Paper-624]
        at de.jeffclan.Drop2Inventory.DropHandler.drop2inventory(DropHandler.java:68) ~[?:?]
        at de.jeffclan.Drop2Inventory.Listener.onBlockBreak(Listener.java:158) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor81.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-624]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:226) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1285) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-624]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by mfnalex** [comment]
How did you achieve this?

**Comment by successed** [comment]
i dont'no, this console error.

**Comment by mfnalex** [comment]
Did this error appear only once? If you see it again, please try to remember what you did at that moment.

**Comment by successed** [comment]
I see it from time to time since the last update.

**Comment by mfnalex** [comment]
You mean it did not appear prior to Drop2Inv 3.8?

I am sure the error can only happen when certain stuff happens and not randomly, e.g. when using a specific tool while looking at air or something. Unfortunately, I cannot do much right now until I can reproduce the problem. How often does this error occur? Like every few seconds, or more like once a day or something?
