### ISSUE TITLE
NullPointerException Listener.java:115

### ISSUE THREAD

**Issue by resi23** [JEFF-Media-GbR/Spigot-Drop2Inventory#23]
``` java.lang.NullPointerException: null
citybuilddev |  at de.jeff_media.Drop2Inventory.Listener.onBlockBreak(Listener.java:115) ~[?:?]
citybuilddev |  at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor110.execute(Unknown Source) ~[?:?]
citybuilddev |  at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:249) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1389) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-41]
citybuilddev |  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by mfnalex** [comment]
Fixed in 3.9.2
