### ISSUE TITLE
idk what's going on 

### ISSUE THREAD

**Issue by princepnp** [JEFF-Media-GbR/Spigot-Drop2Inventory#44]
[20:54:14] [Server thread/ERROR]: Fatal error trying to convert Drop2InventoryPlus v3.5.1:de/jeff_media/drop2inventory/Main.class
java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassReader.readConst(ClassReader.java:3849) ~[asm-9.3.jar:9.3]
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2421) ~[asm-9.3.jar:9.3]
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514) ~[asm-9.3.jar:9.3]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744) ~[asm-9.3.jar:9.3]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424) ~[asm-9.3.jar:9.3]
	at org.bukkit.craftbukkit.v1_19_R1.util.Commodore.convert(Commodore.java:174) ~[paper-1.19.2.jar:git-Paper-260]
	at org.bukkit.craftbukkit.v1_19_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:398) ~[paper-1.19.2.jar:git-Paper-260]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:200) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:129) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:488) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:411) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:319) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.2.jar:git-Paper-260]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-260]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:54:14] [Server thread/ERROR]: Could not load 'plugins\Drop2InventoryPlus-3.5.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Illegal type at constant pool entry 16 in class de.jeff_media.drop2inventory.Main
Exception Details:
  Location:
    de/jeff_media/drop2inventory/Main.byte()V @312: ldc
  Reason:
    Constant pool index 16 is invalid
  Bytecode:
    0000000: 2a4c 2b59 5ab7 009c b600 9fb6 0068 12a1
    0000010: b800 6c03 0459 58b6 00a4 9900 0b2b 0459
    0000020: 5958 b600 a62b b600 6812 a8b8 006c b600
    0000030: ab99 000b 2b04 5959 58b5 00ad 2bb6 0068
    0000040: 12af b800 6cb6 00ab 9900 0b2b 0459 5958
    0000050: b500 b12b 595a bb00 b359 b700 b5b5 00b7
    0000060: bb00 b32b 5b59 5859 b700 b5b5 00b9 bb00
    0000070: b32b 5958 59b7 00b5 b500 bbb4 00ad 9900
    0000080: 132b b600 6812 a8b8 006c b600 bfa7 0010
    0000090: bf2b b600 6812 c1b8 006c b600 bfc0 00b3
    00000a0: b600 c74b 2ab9 00cd 0100 9900 872a b900
    00000b0: d101 00c0 0053 594d b600 d5b8 00db 594e
    00000c0: c700 252b b600 dfbb 00e1 59b7 00e2 0312
    00000d0: e4b8 006c b600 e82c b600 ecb6 00ef b600
    00000e0: f5a7 ffc3 bf2b 59b4 00b7 2db6 00f9 57bb
    00000f0: 00e1 2b59 5859 b700 e212 fbb8 006c b600
    0000100: ec2b b400 ad99 000b 12fd b800 6ca7 0008
    0000110: 12ff b800 6cb6 00ec 1301 01b8 006c b600
    0000120: ec2d b601 04b6 00ec b600 efb6 0106 a7ff
    0000130: 762b b400 b12b 5f00 1210 b600 6812 afb8
    0000140: 006c b600 bf00 100e b600 6813 0108 b800
    0000150: 6cb6 00bf b901 0901 0059 4bb9 00cd 0100
    0000160: 005f 5c2a b900 d101 00c0 0053 4d2b b400
    0000170: b92c b601 0cb6 00f9 57bb 00e1 2b59 5859
    0000180: b700 e213 010e b800 6cb6 00ec 2b5a b400
    0000190: b100 0c0a 12fd b800 6c00 0907 12ff b800
    00001a0: 6cb6 00ec 1301 01b8 006c b600 ec2c b601
    00001b0: 0cb6 00ec b600 efb6 0106 2aa7 ffa0 2bb6
    00001c0: 0068 1301 10b8 006c b600 bfb9 0109 0100
    00001d0: 594b b900 cd01 0040 003c 2ab9 00d1 0100
    00001e0: c000 534d 2a2b b400 bb2c b601 0cb6 00f9
    00001f0: bb00 e12b 5a59 5859 b700 e213 0112 b800
    0000200: 6cb6 00ec 2cb6 010c b600 ecb6 00ef b601
    0000210: 0657 a7ff c02b b600 6813 0114 b800 6c09
    0000220: b601 18b8 011b 006c 0068 2b59 5abb 00e1
    0000230: 2b59 5859 b700 e213 011d b800 6cb6 00ec
    0000240: 2b5a b600 6813 0114 b800 6cb6 0120 b601
    0000250: 23b6 00ef b601 06bb 00e1 2b5b 5958 59b7
    0000260: 00e2 1301 25b8 006c b600 ecb8 011b b601
    0000270: 23b6 00ef b601 06b7 0127 bb01 2959 2bb7
    0000280: 012c 4b04 2ab6 012e 0459 58b5 0130 b601
    0000290: 33b1                                   
  Stackmap Table:
    append_frame(@37,Object[#2])
    same_frame(@60)
    same_frame(@83)
    full_frame(@144,{},{Object[#49]})
    append_frame(@145,Object[#2],Object[#2])
    same_locals_1_stack_item_frame(@157,Object[#195])
    full_frame(@164,{Object[#201],Object[#2]},{})
    full_frame(@228,{},{Object[#49]})
    full_frame(@229,{Object[#201],Object[#2],Object[#83],Object[#215]},{})
    full_frame(@272,{Object[#201],Object[#2],Object[#83],Object[#215]},{Object[#2],Object[#225]})
    full_frame(@277,{Object[#201],Object[#2],Object[#83],Object[#215]},{Object[#2],Object[#225],Object[#83]})
    chop_frame(@305,2)
    same_locals_1_stack_item_frame(@328,Object[#2])
    same_locals_1_stack_item_frame(@340,Object[#195])
    same_locals_1_stack_item_frame(@347,Object[#201])
    full_frame(@412,{Object[#201],Object[#2],Object[#83]},{Object[#2],Object[#225]})
    full_frame(@417,{Object[#201],Object[#2],Object[#83]},{Object[#2],Object[#225],Object[#83]})
    chop_frame(@446,1)
    same_locals_1_stack_item_frame(@466,Object[#201])
    same_frame_extended(@533)
    full_frame(@657,{Object[#309],Object[#2]},{})

	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:411) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:319) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.2.jar:git-Paper-260]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-260]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.VerifyError: Illegal type at constant pool entry 16 in class de.jeff_media.drop2inventory.Main
Exception Details:
  Location:
    de/jeff_media/drop2inventory/Main.byte()V @312: ldc
  Reason:
    Constant pool index 16 is invalid
  Bytecode:
    0000000: 2a4c 2b59 5ab7 009c b600 9fb6 0068 12a1
    0000010: b800 6c03 0459 58b6 00a4 9900 0b2b 0459
    0000020: 5958 b600 a62b b600 6812 a8b8 006c b600
    0000030: ab99 000b 2b04 5959 58b5 00ad 2bb6 0068
    0000040: 12af b800 6cb6 00ab 9900 0b2b 0459 5958
    0000050: b500 b12b 595a bb00 b359 b700 b5b5 00b7
    0000060: bb00 b32b 5b59 5859 b700 b5b5 00b9 bb00
    0000070: b32b 5958 59b7 00b5 b500 bbb4 00ad 9900
    0000080: 132b b600 6812 a8b8 006c b600 bfa7 0010
    0000090: bf2b b600 6812 c1b8 006c b600 bfc0 00b3
    00000a0: b600 c74b 2ab9 00cd 0100 9900 872a b900
    00000b0: d101 00c0 0053 594d b600 d5b8 00db 594e
    00000c0: c700 252b b600 dfbb 00e1 59b7 00e2 0312
    00000d0: e4b8 006c b600 e82c b600 ecb6 00ef b600
    00000e0: f5a7 ffc3 bf2b 59b4 00b7 2db6 00f9 57bb
    00000f0: 00e1 2b59 5859 b700 e212 fbb8 006c b600
    0000100: ec2b b400 ad99 000b 12fd b800 6ca7 0008
    0000110: 12ff b800 6cb6 00ec 1301 01b8 006c b600
    0000120: ec2d b601 04b6 00ec b600 efb6 0106 a7ff
    0000130: 762b b400 b12b 5f00 1210 b600 6812 afb8
    0000140: 006c b600 bf00 100e b600 6813 0108 b800
    0000150: 6cb6 00bf b901 0901 0059 4bb9 00cd 0100
    0000160: 005f 5c2a b900 d101 00c0 0053 4d2b b400
    0000170: b92c b601 0cb6 00f9 57bb 00e1 2b59 5859
    0000180: b700 e213 010e b800 6cb6 00ec 2b5a b400
    0000190: b100 0c0a 12fd b800 6c00 0907 12ff b800
    00001a0: 6cb6 00ec 1301 01b8 006c b600 ec2c b601
    00001b0: 0cb6 00ec b600 efb6 0106 2aa7 ffa0 2bb6
    00001c0: 0068 1301 10b8 006c b600 bfb9 0109 0100
    00001d0: 594b b900 cd01 0040 003c 2ab9 00d1 0100
    00001e0: c000 534d 2a2b b400 bb2c b601 0cb6 00f9
    00001f0: bb00 e12b 5a59 5859 b700 e213 0112 b800
    0000200: 6cb6 00ec 2cb6 010c b600 ecb6 00ef b601
    0000210: 0657 a7ff c02b b600 6813 0114 b800 6c09
    0000220: b601 18b8 011b 006c 0068 2b59 5abb 00e1
    0000230: 2b59 5859 b700 e213 011d b800 6cb6 00ec
    0000240: 2b5a b600 6813 0114 b800 6cb6 0120 b601
    0000250: 23b6 00ef b601 06bb 00e1 2b5b 5958 59b7
    0000260: 00e2 1301 25b8 006c b600 ecb8 011b b601
    0000270: 23b6 00ef b601 06b7 0127 bb01 2959 2bb7
    0000280: 012c 4b04 2ab6 012e 0459 58b5 0130 b601
    0000290: 33b1                                   
  Stackmap Table:
    append_frame(@37,Object[#2])
    same_frame(@60)
    same_frame(@83)
    full_frame(@144,{},{Object[#49]})
    append_frame(@145,Object[#2],Object[#2])
    same_locals_1_stack_item_frame(@157,Object[#195])
    full_frame(@164,{Object[#201],Object[#2]},{})
    full_frame(@228,{},{Object[#49]})
    full_frame(@229,{Object[#201],Object[#2],Object[#83],Object[#215]},{})
    full_frame(@272,{Object[#201],Object[#2],Object[#83],Object[#215]},{Object[#2],Object[#225]})
    full_frame(@277,{Object[#201],Object[#2],Object[#83],Object[#215]},{Object[#2],Object[#225],Object[#83]})
    chop_frame(@305,2)
    same_locals_1_stack_item_frame(@328,Object[#2])
    same_locals_1_stack_item_frame(@340,Object[#195])
    same_locals_1_stack_item_frame(@347,Object[#201])
    full_frame(@412,{Object[#201],Object[#2],Object[#83]},{Object[#2],Object[#225]})
    full_frame(@417,{Object[#201],Object[#2],Object[#83]},{Object[#2],Object[#225],Object[#83]})
    chop_frame(@446,1)
    same_locals_1_stack_item_frame(@466,Object[#201])
    same_frame_extended(@533)
    full_frame(@657,{Object[#309],Object[#2]},{})

	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:488) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 7 more

**Comment by mfnalex** [comment]
Hi, this repository is for the free, outdated version for D2I. Please open a ticket on my Discord (see channel #tickets): https://discord.jeff-media.com
